# permissions for end users to edit gitlabs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-editor-role
rules:
- apiGroups:
  - devops.gitlab.domain
  resources:
  - gitlabs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.gitlab.domain
  resources:
  - gitlabs/status
  verbs:
  - get
