---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - service
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.gitlab.domain
  resources:
  - gitlabs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.gitlab.domain
  resources:
  - gitlabs/finalizers
  verbs:
  - update
- apiGroups:
  - devops.gitlab.domain
  resources:
  - gitlabs/status
  verbs:
  - get
  - patch
  - update
