apiVersion: devops.gitlab.domain/v1
kind: Gitlab
metadata:
  name: gitlab-sample
  namespace: "gitlab"
spec:
  image: "gitlab/gitlab-ce"
  port:
    - containerport: 80
      exportport: 30080
      name: "http"
      exporttype: "NodePort"
    - name: "https"
      containerport: 443
      exportport: 7443
    - name: "ssh"
      containerport: 22
      exportport: 30022
  defaultpassword: "12345678"
